### ISSUE TITLE
能做个使用说明吗

### ISSUE THREAD

**Issue by njzhenghao** [zhanglei-workspace/shopping-management-system#1]
新手表示不一定都能看得懂

**Comment by zhanglei-workspace** [comment]
基本介绍在首页 README.md 。 你是具体哪里不懂呢？

**Comment by njzhenghao** [comment]
感觉虚度了很多光阴，都已经大三了，马上大四，现在正在转方向，java，看到你的练习项目star很高的，想问问，你的这个项目是给项目说明让我们自己做吗，但是我又看到里面又有java的源码，就是我fork下来应该怎么做呢

**Comment by zhanglei-workspace** [comment]
README里面是项目的基本介绍（类似需求文档），你看到的源码就是文档代码实现，是可以直接跑起来的。你可以学习并改进源码。
离大四找工作还有四个月，时间足够了。

**Comment by njzhenghao** [comment]
好的，谢谢你，作为一个老程序员，您能不能给我指一下学习路线呢，我主要走后台

**Comment by zhanglei-workspace** [comment]
我是一个很年轻的菜鸟。。。我个人觉得只要把在readme里列出的知识菜单学会找份实习应该不难，到公司后跟着技术大牛们做项目，慢慢提升，不要着急。

**Comment by njzhenghao** [comment]
谢谢你，麻烦了
