### ISSUE TITLE
java入门级项目导入有错，很多jar包都没有，ojdbc5.jar,mybatis-3.3.1-sources.jar,mybatis-3.3.1-.jar,log4j-1.2.17.jar

### ISSUE THREAD

**Issue by Creaglow** [zhanglei-workspace/shopping-management-system#6]
没有ojdbc5.jar,mybatis-3.3.1-sources.jar,mybatis-3.3.1-.jar,log4j-1.2.17.jar.
还有不知道是不是我导入java菜鸟级项目的方式有问题，导不进去，第一个也是

**Comment by zhanglei-workspace** [comment]
1.在.gitignore中忽略掉了 *.jar 。
2.前两个项目直接import的确导入不进去，因为没有上传.classpath。解决办法：建立一个同名字工程，拖拉文件进工程就可以啦。
